
// refenceError
try {
    let a = 10;
    let c = a+b;
} catch (error) {
    console.log(error);
}